name: Stale Issues & PRs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mark_stale:
    name: Mark issues and PRs as Stale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-pr-stale:    90
          days-before-pr-close:    10
          days-before-issue-stale: 60
          days-before-issue-close: 3
          stale-issue-message: >
            This issue is Stale because it has been open for 100 days with no activity.
            Contribute a fix or comment on the issue, or it will be closed in a few days.
          stale-pr-message: >
            This pull request is Stale because it has been open for 100 days with no activity.
            Contribute more commits on the pull request, or it will be closed in a few days.
          close-issue-message: >
            This issue has been marked as Stale and closed due to inactivity after 100 days.
          close-pr-message: >
            This pull request has been marked as Stale and Closed due to inactivity after 100 days.
